### ISSUE TITLE
Can't install virika.exe

### ISSUE THREAD

**Issue by farhanf7n** [kamranahmedse/virika-a-usb-fixer#1]
![image](https://cloud.githubusercontent.com/assets/22557078/22623209/672a9078-eb73-11e6-96bc-86f25342af2e.png)

This is the problem bruh, "Cannot download the application, req files missing. Bandy ko milo"

**Comment by kamranahmedse** [comment]
You need to have dot net framework 4 or higher installed. If still doesn't work then bhaj ja ;)

**Comment by farhanf7n** [comment]
The version of my .net framework is 4.5.1, but it's still not working.. :3

![image](https://cloud.githubusercontent.com/assets/22557078/22625992/b773fa00-ebc4-11e6-9304-522e5b45096a.png)

**Comment by kamranahmedse** [comment]
Bhaj ja

**Comment by farhanf7n** [comment]
Acha.😂😝
